package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.MagicGithubApplication;
import com.openclassrooms.magicgithub.model.User;

import java.util.Collections;
import java.util.List;
import java.util.Random;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

import android.widget.Toast;


public class FakeApiService implements ApiService {

    private final List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // Done : Return users list
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // Done : Shuffle the list of user, then pick one who has not been added yet, or send a toast to inform the user that there is no one to add
        Collections.shuffle(FAKE_USERS_RANDOM);
        boolean generated = false;
        for (User user : FAKE_USERS_RANDOM) {
            if (!users.contains(user)) {
                users.add(user);
                generated = true;
                break;
            }
        }
        if(!generated) Toast.makeText(MagicGithubApplication.getAppContext(), "No more user to add", Toast.LENGTH_SHORT).show();
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // Done : remove a user from the list
        users.remove(user);
    }
}
